language: python
dist: "precise"
python:
  - "2.7.10"
    #  - "3.5"
cache: pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
  - pip install pytest pytest-cov
# command to install dependencies
install: "pip install -r requirements.txt"

script: python -m pytest tests/
