language: python
python:
  - "2.7.10"
  - "3.5"
cache: pip
before_install:
  - pip install pytest pytest-cov
# command to install dependencies
install: "pip install -r requirements.txt"
script: python -m pytest tests/
